### ISSUE TITLE
OnClick open activity

### ISSUE THREAD

**Issue by rowjak** [PatilShreyas/MaterialNavigationView-Android#14]
i've already clone this repo and open it on android studio, works well
but if i want to use activity instead of fragment when onclick navigation item, how to do that ?

Thank's

**Comment by PatilShreyas** [comment]
@rowjak You can use `NavigationView.OnNavigationItemSelectedListener`. See [this](https://stackoverflow.com/questions/42499696/how-to-add-click-event-to-item-on-navigationview-of-android) for more information.

**Comment by rowjak** [comment]
ooke thank you very much, it works,
