### ISSUE TITLE
Do something when Navigation View Item is touched

### ISSUE THREAD

**Issue by yleyvag** [PatilShreyas/MaterialNavigationView-Android#4]
I'm using this library on my project. I have some options on my sidebar menu and I don't want to display the screen inside fragment, I want to start a new activity. How can I start a new activity when some item is touched?

**Comment by PatilShreyas** [comment]
Hi, you can refer this.
https://developer.android.com/guide/navigation/navigation-ui

**Comment by yleyvag** [comment]
Thank you
