### ISSUE TITLE
Suggestions and implementation of New item styles

### ISSUE THREAD

**Issue by PatilShreyas** [PatilShreyas/MaterialNavigationView-Android#5]
If you have good ideas or suggestions or good material design structure available for item style of MaterialNavigationView then you're at right place. You can contribute us if you have cool ideas. You are always welcome. You can open PR or simply show your design here in comments. Thank you.

**Comment by lakhanmeghani** [comment]
Hi, I have suggestion that we could add design in which there will be radius from all sides.

**Comment by PatilShreyas** [comment]
@lakhanmeghani Suggestion is good. Can you send PR?

**Comment by lakhanmeghani** [comment]
Yeah Sure!

**Comment by tcqq** [comment]
@PatilShreyas After the rounded item is pressed, the water ripple effect is out of bounds. Gmail is also a rounded corner style, but it won't cross the border after pressing the item.
![image](https://user-images.githubusercontent.com/10644057/67529568-1ca98880-f6ef-11e9-9daa-648f9bc774ae.png)
![image](https://user-images.githubusercontent.com/10644057/67529573-1f0be280-f6ef-11e9-84f7-ada229815d79.png)

**Comment by PatilShreyas** [comment]
@tcqq Thanks for reporting that. I'm also looking to solve it. If you have solution on this, please open PR.

**Comment by PatilShreyas** [comment]
@tcqq I have opened new issue here #8.
