### ISSUE TITLE
[ENHANCEMENT] Out of bound ripple on item click.

### ISSUE THREAD

**Issue by PatilShreyas** [PatilShreyas/MaterialNavigationView-Android#8]
After the rounded item is pressed, the water ripple effect is out of bounds. Gmail is also a rounded corner style, but it won't cross the border after pressing the item.
![image](https://user-images.githubusercontent.com/10644057/67529568-1ca98880-f6ef-11e9-9daa-648f9bc774ae.png)
![image](https://user-images.githubusercontent.com/10644057/67529573-1f0be280-f6ef-11e9-84f7-ada229815d79.png)

_Originally posted by @tcqq in https://github.com/PatilShreyas/MaterialNavigationView-Android/issues/5#issuecomment-546125699_

**Comment by PremChavhan** [comment]
PatilShreyas please check  #9 these pull request in which I tried to solve the problem of unbounded ripple

**Comment by zainfikrih** [comment]
@PatilShreyas Hi, please check #11 
I tried to fix it. This #is the development of #9 # #

**Comment by PatilShreyas** [comment]
Thanks @zainfikrih for working on this.

**Comment by PatilShreyas** [comment]
This issue is fixed and implemented in `v1.2`
